### ISSUE TITLE
fhir-to-rdf mocha test failure

### ISSUE THREAD

**Issue by dbooth-boston** [rdf-pipeline/noflo-rdf-pipeline#66]
$ mocha test/fhir-to-rdf-mocha.js 

  fhir-to-rdf
ERROR:  'Could not compile stylesheet'
FATAL ERROR:  'Error checking type of the expression 'funcall(current-dateTime, [])'.'
           :Error checking type of the expression 'funcall(current-dateTime, [])'.
    1) should translate patient demographics fhir to RDF in a noflo network

  0 passing (8s)
  1 failing

  1) fhir-to-rdf should translate patient demographics fhir to RDF in a noflo network:
     Uncaught Error: Error running instance method
javax.xml.transform.TransformerConfigurationException: Error checking type of the expression 'funcall(current-dateTime, [])'.
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:791)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: Error checking type of the expression 'funcall(current-dateTime, [])'.
    at com.sun.org.apache.xalan.internal.xsltc.compiler.FunctionCall.typeCheckStandard(FunctionCall.java:461)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.FunctionCall.typeCheck(FunctionCall.java:370)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Param.typeCheck(Param.java:158)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:651)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:412)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:483)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:568)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:977)
##     ... 5 more

Error checking type of the expression 'funcall(current-dateTime, [])'.
    at com.sun.org.apache.xalan.internal.xsltc.compiler.FunctionCall.typeCheckStandard(FunctionCall.java:461)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.FunctionCall.typeCheck(FunctionCall.java:370)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Param.typeCheck(Param.java:158)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:651)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:412)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:483)
    at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:568)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:977)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:791)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)

```
at Error (native)
at Object.module.exports.transformSync (node_modules/xslt4node/lib/xslt4node.js:285:31)
at Interface.<anonymous> (components/xml-to-rdf.js:127:34)
at Interface._onLine (readline.js:212:10)
at Interface.<anonymous> (readline.js:342:12)
at Array.forEach (native)
at Interface._normalWrite (readline.js:341:11)
at ReadStream.ondata (readline.js:88:10)
at readableAddChunk (_stream_readable.js:153:18)
at ReadStream.Readable.push (_stream_readable.js:111:10)
at onread (fs.js:1739:12)
at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

**Comment by dbooth-boston** [comment]
Glenna found the npm dependency that caused this, and fixed it in PR 187 https://github.com/rdf-pipeline/noflo-rdf-components/pull/187
